services:
  api:
    container_name: demo_test_api
    environment: 
      - PGUSER=pearlhamilton
      - PGHOST=db
      - PGPASSWORD=dbpass
      - PGDATABASE=plants_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: demo_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=plants_test
      - POSTGRES_PASSWORD=dbpass
volumes:
  test_db:
networks: 
  default:
    name: demo_app_test